/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistasJframe;

import controller.Archivos;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import modelo.Archivo;
import modelo.ArchivosDatos;
import modelo.Carpetas;
import modelo.Configuraciones;
import vistas.CuadroCarpetasPanel;


public class InputFile extends javax.swing.JFrame {
    private boolean activo = true;
    private int opcionCuadro = 1;
    private int indice;
    public InputFile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtJugador2 = new javax.swing.JTextField();
        imagen1 = new controller.Imagen();
        imagen2 = new controller.Imagen();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        txtJugador2.setBackground(new java.awt.Color(249, 230, 254));
        txtJugador2.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        txtJugador2.setForeground(new java.awt.Color(202, 105, 220));
        txtJugador2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtJugador2.setText("PLAYER 2");
        txtJugador2.setBorder(null);
        txtJugador2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtJugador2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtJugador2FocusLost(evt);
            }
        });
        txtJugador2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtJugador2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtJugador2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtJugador2MouseExited(evt);
            }
        });
        txtJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJugador2ActionPerformed(evt);
            }
        });
        txtJugador2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJugador2KeyTyped(evt);
            }
        });

        imagen1.setText("imagen1");
        imagen1.setRuta("/recursos/carpetas.png");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtJugador2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addComponent(imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 190, 40);

        imagen2.setText("imagen2");
        imagen2.setRuta("/recursos/indicador.png");
        jPanel1.add(imagen2);
        imagen2.setBounds(190, 0, 46, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJugador2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJugador2FocusGained
        if( this.txtJugador2.getText().equals("PLAYER 2")){
            this.txtJugador2.setText("");
        }
    }//GEN-LAST:event_txtJugador2FocusGained

    private void txtJugador2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJugador2FocusLost
        if( this.txtJugador2.getText().length() == 0){
            this.txtJugador2.setText("PLAYER 2");
        }
    }//GEN-LAST:event_txtJugador2FocusLost

    private void txtJugador2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJugador2MouseClicked

        Border borde = BorderFactory.createLineBorder(new Color(165,40,174),2);
        this.txtJugador2.setBorder(borde);

    }//GEN-LAST:event_txtJugador2MouseClicked

    private void txtJugador2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJugador2MouseEntered
        Border borde = BorderFactory.createLineBorder(new Color(165,40,174),2);
        this.txtJugador2.setBorder(borde);
    }//GEN-LAST:event_txtJugador2MouseEntered

    private void txtJugador2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJugador2MouseExited
        this.txtJugador2.setBorder(null);
    }//GEN-LAST:event_txtJugador2MouseExited

    private void txtJugador2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJugador2KeyTyped
        if( this.txtJugador2.getText().length() <= 8){
            char caracter = Character.toUpperCase( evt.getKeyChar());
            evt.setKeyChar(caracter);
            return;
        }
        evt.consume();
    }//GEN-LAST:event_txtJugador2KeyTyped

    private void txtJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJugador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJugador2ActionPerformed
    public void focusText(CuadroCarpetasPanel padreObjeto,ArchivosDatos datos){
        this.txtJugador2.setVisible(true);
        this.txtJugador2.requestFocusInWindow();
        InputFile acceso = this;
        this.txtJugador2.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                
                System.out.println("valores : "+txtJugador2.getText());
                String nombre = txtJugador2.getText();
                if(nombre.length() == 0 || nombre.equals("nombre Carpeta") || !activo ){
                    padreObjeto.CargarDatos();
                    return;
                }
                activo = false;
                if(opcionCuadro == 1){
                    Archivos archivoCreate = new Archivos();
                    archivoCreate.crearCarpeta(nombre,Configuraciones.RutaArchivo());
                    Archivo carpetaaux = new Archivo();
                    carpetaaux.addDatos(nombre, null, Configuraciones.RutaArchivo() );
                    datos.AgregarDatos(carpetaaux);
                    padreObjeto.CargarDatos();
                    
                }else if(opcionCuadro == 2){
                    Archivo updateValor = datos.setDato(indice);
                    updateValor.setNombre(nombre);
                    datos.UpdateDato(updateValor , indice);
                    padreObjeto.CargarDatos();
                }
                acceso.dispose();
            }
        });
        
        this.txtJugador2.addFocusListener(new FocusAdapter(){
            @Override
            public void focusLost(FocusEvent e){
                System.out.println("valores : "+txtJugador2.getText());
                String nombre = txtJugador2.getText();
                if(nombre.length() == 0 || nombre.equals("nombre Carpeta") || !activo){
                    padreObjeto.CargarDatos();
                    return;
                }
                activo = false;
                if(opcionCuadro == 1){
                    Archivos archivoCreate = new Archivos();
                    archivoCreate.crearCarpeta(nombre,Configuraciones.RutaArchivo());
                    Archivo carpetaaux = new Archivo();
                    carpetaaux.addDatos(nombre, null, Configuraciones.RutaArchivo() );
                    datos.AgregarDatos(carpetaaux);
                    System.out.println("Actualizado xd");
                    padreObjeto.CargarDatos();
                }else if(opcionCuadro == 2){
                    Archivo updateValor = datos.setDato(indice);
                    updateValor.setNombre(nombre);
                    datos.UpdateDato(updateValor , indice);
                    padreObjeto.CargarDatos();
                }
                acceso.dispose();
            }
        });
        
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controller.Imagen imagen1;
    private controller.Imagen imagen2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtJugador2;
    // End of variables declaration//GEN-END:variables
}
